services:
  - type: web
    name: yzuic114-webstudy
    env: python
    plan: free
    buildCommand: >
      curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&
      apt-get install -y nodejs &&
      cd frontend &&
      npm install &&
      npm run build &&
      cd .. &&
      pip install -r requirements.txt
    startCommand: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py create_default_user &&
             python manage.py create_default_class &&
             gunicorn yzuic114_webstudy.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: yzuic114-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: yzuic114-webstudy.onrender.com
      - key: DJANGO_SUPERUSER_ID
        sync: false  # 手動設定
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false  # 手動設定

databases:
  - name: yzuic114-db
    databaseName: yzuic114_stamindtask
    user: henry
    plan: free
