# Generated by Django 4.2.17 on 2025-02-07 02:26

import backend.models.users
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", backend.models.users.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="chat_history",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(
                    default={"content": "", "sender": "", "time": "2025-02-07 02:26:06"}
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
