# Generated by Django 4.2.17 on 2025-02-18 05:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_user_student_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="目標名稱")),
                (
                    "targets",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        default=list,
                        size=None,
                        verbose_name="目標內容",
                    ),
                ),
                (
                    "sub_targets",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        default=list,
                        size=None,
                        verbose_name="子任務",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "目標",
                "verbose_name_plural": "目標列表",
                "db_table": "targets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="target",
            field=models.OneToOneField(
                blank=True,
                help_text="該任務的學習目標+子任務列舉",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task",
                to="backend.target",
                verbose_name="學習目標",
            ),
        ),
    ]
