# Generated by Django 4.2.17 on 2025-02-19 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_target_task_target"),
    ]

    operations = [
        migrations.AlterModelTable(
            name='target',
            table='targets',
        ),
    ]
