# Generated by Django 4.2.17 on 2025-02-19 16:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_auto_20250219_1622"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="class_name",
        ),
        migrations.AlterField(
            model_name="experience",
            name="content",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="體驗任務內容"
            ),
        ),
        migrations.AlterField(
            model_name="reflectionquestion",
            name="questions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="反思問題列表",
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="sub_targets",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="子任務",
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="targets",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="目標內容",
            ),
        ),
        migrations.AlterField(
            model_name="textbook",
            name="content",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="教材內容"
            ),
        ),
    ]
