# Generated by Django 4.2.17 on 2025-02-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_remove_experience_class_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="diagram_content",
            field=models.JSONField(
                blank=True,
                help_text="包含 node_data 和 link_data 的 JSON 格式資料",
                null=True,
                verbose_name="圖表內容",
            ),
        ),
    ]
