# Generated by Django 4.2.17 on 2025-02-27 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_task_diagram_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="target",
            old_name="sub_targets",
            new_name="sub_target_list",
        ),
    ]
