# Generated by Django 4.2.17 on 2025-02-27 16:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_remove_target_targets_target_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="description",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="目標描述",
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="target",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=120),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="目標名稱",
            ),
        ),
    ]
