# Generated by Django 4.2.17 on 2025-02-27 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_alter_target_description_alter_target_target"),
    ]

    operations = [
        migrations.RenameField(
            model_name="target",
            old_name="description",
            new_name="descriptions",
        ),
        migrations.RenameField(
            model_name="target",
            old_name="target",
            new_name="targets",
        ),
    ]
