# Generated by Django 4.2.17 on 2025-02-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_rename_description_target_descriptions_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE targets
            ALTER COLUMN sub_target_list TYPE jsonb
            USING to_jsonb(sub_target_list);
            """,
            reverse_sql="""
                ALTER TABLE targets
                ALTER COLUMN sub_target_list TYPE character varying[]
                USING array_to_string(sub_target_list, ',')::character varying[];
            """
        ),
    ]
