# Generated by Django 4.2.17 on 2025-02-28 17:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_alter_target_sub_target_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenttaskplan",
            name="content",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="任務計畫設定內容"
            ),
        ),
        migrations.AlterField(
            model_name="studenttaskprocess",
            name="content",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="任務執行設定內容"
            ),
        ),
        migrations.AlterField(
            model_name="studenttaskprocessnote",
            name="content",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="studenttaskreflection",
            name="reflects",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="反思回饋列表",
            ),
        ),
        migrations.AlterField(
            model_name="studenttaskreflection",
            name="score",
            field=models.IntegerField(blank=True, null=True, verbose_name="自我評分"),
        ),
        migrations.AlterField(
            model_name="target",
            name="sub_target_list",
            field=models.JSONField(
                blank=True,
                help_text="包含 title 和 description 的 Array<JSON> 格式資料",
                null=True,
                verbose_name="子任務",
            ),
        ),
    ]
