# Generated by Django 4.2.17 on 2025-03-03 11:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_alter_studenttaskplan_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studenttaskplan",
            name="content",
        ),
        migrations.AddField(
            model_name="studenttaskplan",
            name="plan_list",
            field=models.JSONField(
                blank=True,
                help_text="包含 strategy, description 和 time 的 Array<JSON> 格式資料",
                null=True,
                verbose_name="子任務",
            ),
        ),
        migrations.AddField(
            model_name="studenttaskplan",
            name="select_sub_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BooleanField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="選擇的子目標",
            ),
        ),
    ]
