# Generated by Django 4.2.17 on 2025-03-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0015_remove_studenttaskplan_select_sub_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="studenttaskplan",
            name="select_sub_list",
            field=models.JSONField(
                blank=True,
                help_text="包含是否選擇子任務的 Boolean 的 Array<JSON> 格式資料",
                null=True,
                verbose_name="子任務的選擇",
            ),
        ),
    ]
