# Generated by Django 4.2.17 on 2025-03-06 03:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0016_studenttaskplan_select_sub_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="textbook",
            name="file_dir",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="教材存放位置的資料夾名稱",
            ),
        ),
    ]
