# Generated by Django 4.2.17 on 2025-03-06 05:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0017_textbook_file_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="textbook",
            name="file_amount",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="教材總共有幾頁",
            ),
        ),
    ]
