# Generated by Django 4.2.17 on 2025-03-11 03:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0018_textbook_file_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chathistory",
            name="chat_history",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(blank=True, default=dict, null=True),
                blank=True,
                null=True,
                size=None,
                verbose_name="聊天訊息紀錄",
            ),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="action_record",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(blank=True, default=dict, null=True),
                blank=True,
                null=True,
                size=None,
                verbose_name="記錄內容",
            ),
        ),
        migrations.CreateModel(
            name="StudentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="學生筆記內容"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_notes",
                        to="backend.classname",
                        verbose_name="班級",
                    ),
                ),
            ],
            options={
                "verbose_name": "學生筆記",
                "verbose_name_plural": "學生筆記列表",
                "db_table": "student_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="student_note",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="backend.studentnote",
                verbose_name="學生筆記內容",
            ),
        ),
    ]
