# Generated by Django 4.2.17 on 2025-03-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0020_remove_studenttaskprocess_process_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenttaskprocesscode",
            name="css_code",
            field=models.TextField(
                blank=True,
                default="/* Write you css code here */",
                verbose_name="CSS 程式",
            ),
        ),
        migrations.AlterField(
            model_name="studenttaskprocesscode",
            name="js_code",
            field=models.TextField(
                blank=True,
                default="// Write your JavaScript Code here",
                verbose_name="JavaScript 程式",
            ),
        ),
    ]
