# Generated by Django 4.2.17 on 2025-03-17 09:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0021_alter_studenttaskprocesscode_css_code_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                   ALTER TABLE student_task_reflections
                   ALTER COLUMN reflects TYPE jsonb
                   USING to_jsonb(reflects);
               """,
            reverse_sql="""
                   ALTER TABLE student_task_reflections
                   ALTER COLUMN reflects TYPE text[];
               """,
        ),
    ]