# Generated by Django 4.2.17 on 2025-03-17 09:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0022_alter_studenttaskreflection_reflects_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                    ALTER TABLE reflection_questions
                    ALTER COLUMN questions TYPE jsonb
                    USING to_jsonb(questions);
                """,
            reverse_sql="""
                    ALTER TABLE reflection_questions
                    ALTER COLUMN questions TYPE text[];
                """,
        ),
    ]
