# Generated by Django 4.2.17 on 2025-03-17 09:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0023_alter_reflectionquestion_questions_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                    ALTER TABLE student_task_reflections
                    ALTER COLUMN score TYPE integer[]
                    USING ARRAY[score];
                    ALTER TABLE reflection_questions
                    DROP COLUMN questions_json;
                    ALTER TABLE student_task_reflections
                    DROP COLUMN reflects_json;
                """,
            reverse_sql="""
                    ALTER TABLE student_task_reflections
                    ALTER COLUMN score TYPE integer
                    USING score[1];
                    ALTER TABLE reflection_questions
                    ADD COLUMN questions_json JSON NULL;
                    ALTER TABLE student_task_reflections
                    ADD COLUMN reflects_json JSON NULL;
                """,
        ),
        migrations.AlterField(
            model_name="reflectionquestion",
            name="questions",
            field=models.JSONField(blank=True, null=True, verbose_name="反思回饋 JSON 格式"),
        ),
        migrations.AlterField(
            model_name="studenttaskreflection",
            name="reflects",
            field=models.JSONField(blank=True, null=True, verbose_name="反思回饋 JSON 格式"),
        ),
        migrations.AlterField(
            model_name="studenttaskreflection",
            name="score",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="自我評分列表",
            ),
        ),
    ]
