# Generated by Django 4.2.17 on 2025-03-20 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0024_alter_reflectionquestion_questions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenttask",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_task",
                to=settings.AUTH_USER_MODEL,
                verbose_name="歸屬學生",
            ),
        ),
    ]
