# Generated by Django 4.2.17 on 2025-03-23 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0025_alter_studenttask_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chathistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "聊天記錄",
                "verbose_name_plural": "聊天記錄列表",
            },
        ),
    ]
