# Generated by Django 4.2.17 on 2025-03-25 02:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_chathistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-updated_at'], 'verbose_name': '聊天記錄', 'verbose_name_plural': '聊天記錄列表'},
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='chat_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict, null=True), blank=True, default=list, null=True, size=None, verbose_name='聊天訊息紀錄'),
        ),
    ]
