# Generated by Django 4.2.17 on 2025-03-27 04:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_chathistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='action_record',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict, null=True), blank=True, default=list, help_text='\nverb\t     String\t    行為動詞，例如 "點擊", "完成"\nobject_id\t String\t    被操作對象的 ID，例如網頁上的按鈕或區塊的 ID\nobject_type\t String\t    被操作對象的類型，例如 "按鈕", "頁面"\nobject_name\t String\t    被操作對象的名稱（可選，便於查閱）\ncontext\t     JSONField\t行為的上下文資訊，例如設備、瀏覽器等\n        ', null=True, size=None, verbose_name='記錄內容'),
        ),
    ]
