# Generated by Django 4.2.17 on 2025-03-28 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0028_alter_studentrecord_action_record"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentrecord",
            name="action_record",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_record",
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="context",
            field=models.JSONField(default=dict, verbose_name="行為上下文敘述以及完整訊息"),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="object_id",
            field=models.CharField(default="", max_length=100, verbose_name="操作對象 id"),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="object_name",
            field=models.CharField(default="", max_length=100, verbose_name="操作對象名稱"),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="object_type",
            field=models.CharField(default="", max_length=50, verbose_name="操作對象類型"),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="time",
            field=models.CharField(default="", max_length=50, verbose_name="行為發生時間"),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="timer",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="時間經過"
            ),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="學生",
            ),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="verb",
            field=models.CharField(default="", max_length=50, verbose_name="行為動詞"),
        ),
    ]
