# Generated by Django 4.2.17 on 2025-04-09 09:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0029_remove_studentrecord_action_record_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="student_feedback",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="學生回饋",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="teacher_feedback",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="老師回饋",
            ),
        ),
    ]
