# Generated by Django 4.2.17 on 2025-04-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0030_alter_feedback_student_feedback_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studenttaskreflection",
            old_name="score",
            new_name="self_scoring",
        ),
        migrations.AddField(
            model_name="studenttaskreflection",
            name="completed_targets",
            field=models.JSONField(
                blank=True,
                help_text="包含是否完成子任務的 Boolean 的 Array<JSON> 格式資料",
                null=True,
                verbose_name="是否完成子任務列表",
            ),
        ),
    ]
