# Generated by Django 4.2.17 on 2025-04-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0031_rename_score_studenttaskreflection_self_scoring_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessHints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hints",
                    models.JSONField(
                        blank=True, null=True, verbose_name="計劃執行 JSON 格式"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "計劃執行提示",
                "verbose_name_plural": "計劃執行提示列表",
                "db_table": "process_hints",
                "ordering": ["-created_at"],
            },
        ),
    ]
