# Generated by Django 4.2.17 on 2025-04-17 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0032_processhints"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="process_hint",
            field=models.OneToOneField(
                blank=True,
                help_text="協助學生解題的提示",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task",
                to="backend.processhints",
                verbose_name="計劃執行提示",
            ),
        ),
    ]
