# Generated by Django 4.2.17 on 2025-04-30 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0034_studenttaskprocess_process_hint_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="studenttask",
            name="chat_history",
            field=models.OneToOneField(
                blank=True,
                help_text="該課程中與機器人的對話紀錄",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_task",
                to="backend.chathistory",
                verbose_name="聊天記錄",
            ),
        ),
    ]
