# Generated by Django 4.2.17 on 2025-04-30 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0035_studenttask_chat_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="chat_history",
        ),
    ]
