# Generated by Django 4.2.17 on 2025-05-21 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0036_remove_user_chat_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrecord",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_records",
                to="backend.task",
                verbose_name="所屬課程",
            ),
        ),
    ]
