# Generated by Django 4.2.17 on 2025-05-22 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0037_studentrecord_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenttask",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_tasks",
                to="backend.task",
                verbose_name="任務",
            ),
        ),
    ]
