# Generated by Django 4.2.17 on 2025-06-12 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0038_alter_studenttask_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("student_id", models.CharField(blank=True, max_length=100, null=True)),
                ("success", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "登入存取",
                "verbose_name_plural": "登入存取列表",
                "db_table": "login_attempts",
                "ordering": ["-timestamp"],
            },
        ),
    ]
