# Generated by Django 4.2.17 on 2025-10-29 16:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0039_loginattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="RagCommunities",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="社群ID"
                    ),
                ),
                (
                    "human_readable_id",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="可讀ID"
                    ),
                ),
                (
                    "community",
                    models.IntegerField(
                        db_index=True, help_text="社群的唯一編號", verbose_name="社群編號"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="社群在層級結構中的層級",
                        verbose_name="層級",
                    ),
                ),
                (
                    "parent",
                    models.IntegerField(
                        db_index=True,
                        default=-1,
                        help_text="父社群的編號，-1 表示頂層社群",
                        verbose_name="父社群",
                    ),
                ),
                (
                    "children",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        help_text="子社群的編號列表",
                        size=None,
                        verbose_name="子社群列表",
                    ),
                ),
                (
                    "title",
                    models.CharField(db_index=True, max_length=500, verbose_name="標題"),
                ),
                (
                    "entity_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="實體ID列表",
                    ),
                ),
                (
                    "relationship_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="關係ID列表",
                    ),
                ),
                (
                    "text_unit_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="文本單元ID列表",
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        blank=True, help_text="社群的時間標記", null=True, verbose_name="時期"
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="社群中實體的數量",
                        verbose_name="大小",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "RAG社群",
                "verbose_name_plural": "RAG社群",
                "db_table": "rag_communities",
                "ordering": ["level", "community"],
            },
        ),
        migrations.CreateModel(
            name="RagEntities",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="實體ID"
                    ),
                ),
                (
                    "human_readable_id",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="可讀ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(db_index=True, max_length=500, verbose_name="標題"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="類型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "text_unit_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="文本單元ID列表",
                    ),
                ),
                (
                    "frequency",
                    models.IntegerField(
                        db_index=True, default=0, help_text="實體出現的頻率", verbose_name="頻率"
                    ),
                ),
                (
                    "degree",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="實體在圖中的連接度數",
                        verbose_name="度數",
                    ),
                ),
                ("x", models.FloatField(blank=True, null=True, verbose_name="X座標")),
                ("y", models.FloatField(blank=True, null=True, verbose_name="Y座標")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "RAG實體",
                "verbose_name_plural": "RAG實體",
                "db_table": "rag_entities",
                "ordering": ["human_readable_id"],
            },
        ),
        migrations.CreateModel(
            name="RagRelationships",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="關係ID"
                    ),
                ),
                (
                    "human_readable_id",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="可讀ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(db_index=True, max_length=500, verbose_name="源實體"),
                ),
                (
                    "target",
                    models.CharField(
                        db_index=True, max_length=500, verbose_name="目標實體"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="關係描述"),
                ),
                (
                    "weight",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        help_text="關係的權重或強度",
                        verbose_name="權重",
                    ),
                ),
                (
                    "combined_degree",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="源實體和目標實體的組合度數",
                        verbose_name="組合度數",
                    ),
                ),
                (
                    "text_unit_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="文本單元ID列表",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "RAG關係",
                "verbose_name_plural": "RAG關係",
                "db_table": "rag_relationships",
                "ordering": ["human_readable_id"],
            },
        ),
        migrations.CreateModel(
            name="RagSources",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="文本單元的唯一哈希標識符",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="文本單元ID",
                    ),
                ),
                (
                    "human_readable_id",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="可讀ID"
                    ),
                ),
                ("text", models.TextField(help_text="文本單元的實際內容", verbose_name="文本內容")),
                (
                    "n_tokens",
                    models.IntegerField(
                        db_index=True, help_text="文本的 token 計數", verbose_name="Token數量"
                    ),
                ),
                (
                    "document_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        help_text="關聯的文檔ID列表",
                        null=True,
                        size=None,
                        verbose_name="文檔ID列表",
                    ),
                ),
                (
                    "entity_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        help_text="關聯的實體ID列表",
                        null=True,
                        size=None,
                        verbose_name="實體ID列表",
                    ),
                ),
                (
                    "relationship_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        help_text="關聯的關係ID列表",
                        null=True,
                        size=None,
                        verbose_name="關係ID列表",
                    ),
                ),
                (
                    "covariate_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        help_text="關聯的協變量ID列表",
                        null=True,
                        size=None,
                        verbose_name="協變量ID列表",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "RAG文本單元",
                "verbose_name_plural": "RAG文本單元",
                "db_table": "rag_sources",
                "ordering": ["human_readable_id"],
            },
        ),
        migrations.CreateModel(
            name="RagSummaries",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="報告ID",
                    ),
                ),
                (
                    "human_readable_id",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="可讀ID"
                    ),
                ),
                ("community", models.IntegerField(db_index=True, verbose_name="社群編號")),
                ("level", models.IntegerField(db_index=True, verbose_name="層級")),
                (
                    "parent",
                    models.IntegerField(blank=True, null=True, verbose_name="父層級"),
                ),
                (
                    "children",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="子層級列表",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="標題")),
                ("summary", models.TextField(verbose_name="摘要")),
                ("full_content", models.TextField(verbose_name="完整內容")),
                ("rank", models.FloatField(db_index=True, verbose_name="排名分數")),
                ("rating_explanation", models.TextField(verbose_name="評分說明")),
                ("findings", models.JSONField(default=list, verbose_name="發現列表")),
                (
                    "full_content_json",
                    models.JSONField(blank=True, null=True, verbose_name="完整內容JSON"),
                ),
                ("period", models.DateField(blank=True, null=True, verbose_name="期間")),
                ("size", models.IntegerField(blank=True, null=True, verbose_name="大小")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "RAG社群摘要",
                "verbose_name_plural": "RAG社群摘要",
                "db_table": "rag_summaries",
                "ordering": ["-rank", "human_readable_id"],
            },
        ),
    ]
