# Generated by Django 4.2.17 on 2025-10-29 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0040_ragcommunities_ragentities_ragrelationships_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragcommunities",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_rag_community",
                to="backend.task",
                verbose_name="所屬課程",
            ),
        ),
        migrations.AddField(
            model_name="ragentities",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_rag_entity",
                to="backend.task",
                verbose_name="所屬課程",
            ),
        ),
        migrations.AddField(
            model_name="ragrelationships",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_rag_relationship",
                to="backend.task",
                verbose_name="所屬課程",
            ),
        ),
        migrations.AddField(
            model_name="ragsources",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_rag_source",
                to="backend.task",
                verbose_name="所屬課程",
            ),
        ),
        migrations.AddField(
            model_name="ragsummaries",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_rag_summary",
                to="backend.task",
                verbose_name="所屬課程",
            ),
        ),
        migrations.AddIndex(
            model_name="ragcommunities",
            index=models.Index(
                fields=["task", "human_readable_id"], name="community_task_human_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragentities",
            index=models.Index(
                fields=["task", "human_readable_id"], name="entity_task_human_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragrelationships",
            index=models.Index(
                fields=["task", "human_readable_id"], name="relationship_task_human_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragsources",
            index=models.Index(
                fields=["task", "human_readable_id"], name="source_task_human_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragsummaries",
            index=models.Index(
                fields=["task", "human_readable_id"], name="summary_task_human_idx"
            ),
        ),
    ]
