# Generated by Django 4.2.17 on 2025-11-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0041_ragcommunities_task_ragentities_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studenttaskprocesscode",
            name="assistant_thread_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="助理對話Thread ID"
            ),
        ),
    ]
