# Generated by Django 4.2.17 on 2026-01-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0042_studenttaskprocesscode_assistant_thread_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ragcommunities",
            name="human_readable_id",
            field=models.IntegerField(db_index=True, verbose_name="可讀ID"),
        ),
        migrations.AlterField(
            model_name="ragentities",
            name="human_readable_id",
            field=models.IntegerField(db_index=True, verbose_name="可讀ID"),
        ),
        migrations.AlterField(
            model_name="ragrelationships",
            name="human_readable_id",
            field=models.IntegerField(db_index=True, verbose_name="可讀ID"),
        ),
        migrations.AlterField(
            model_name="ragsources",
            name="human_readable_id",
            field=models.IntegerField(db_index=True, verbose_name="可讀ID"),
        ),
        migrations.AlterField(
            model_name="ragsummaries",
            name="human_readable_id",
            field=models.IntegerField(db_index=True, verbose_name="可讀ID"),
        ),
    ]
