# Generated by Django 5.2.11 on 2026-03-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0043_alter_ragcommunities_human_readable_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="target_nodes",
            field=models.JSONField(
                blank=True,
                help_text="包含 name 和 description 的 Array<JSON> 格式資料",
                null=True,
                verbose_name="目標節點",
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="target_relations",
            field=models.JSONField(
                blank=True,
                help_text="包含 source, target 和 relation 的 Array<JSON> 格式資料",
                null=True,
                verbose_name="目標關係",
            ),
        ),
    ]
