# Generated by Django 5.2.11 on 2026-04-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0044_target_target_nodes_target_target_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="target_graph_descriptions",
            field=models.JSONField(
                blank=True,
                help_text="包和 description 的 Array<JSON> 格式資料",
                null=True,
                verbose_name="目標 graphRag 描述",
            ),
        ),
    ]
